services:
  sheet-music-viewer-dev:
    build:
      context: .
    container_name: sheet-music-viewer-dev
    tty: true
    privileged: true
    volumes:
       - .:/project
       - /dev/bus/usb:/dev/bus/usb
